import type { Company, Extinguisher, Inspection, Invoice, User } from './types'

// Mock Companies
export const mockCompanies: Company[] = [
  {
    id: 'c1',
    name: 'FireSafe Solutions',
    email: 'contact@firesafe.com',
    phone: '+1 (555) 123-4567',
    address: '123 Safety Street, New York, NY 10001',
    isActive: true,
    createdAt: '2024-01-15',
    totalExtinguishers: 245,
    activeInspectors: 5,
    pendingInspections: 12,
  },
  {
    id: 'c2',
    name: 'FireGuard Inc.',
    email: 'info@fireguard.com',
    phone: '+1 (555) 234-5678',
    address: '456 Protection Ave, Los Angeles, CA 90001',
    isActive: true,
    createdAt: '2024-02-20',
    totalExtinguishers: 180,
    activeInspectors: 3,
    pendingInspections: 8,
  },
  {
    id: 'c3',
    name: 'SafetyFirst Corp',
    email: 'hello@safetyfirst.com',
    phone: '+1 (555) 345-6789',
    address: '789 Emergency Blvd, Chicago, IL 60601',
    isActive: false,
    createdAt: '2024-03-10',
    totalExtinguishers: 95,
    activeInspectors: 2,
    pendingInspections: 5,
  },
  {
    id: 'c4',
    name: 'ProFire Services',
    email: 'support@profire.com',
    phone: '+1 (555) 456-7890',
    address: '321 Alert Road, Houston, TX 77001',
    isActive: true,
    createdAt: '2024-04-05',
    totalExtinguishers: 320,
    activeInspectors: 7,
    pendingInspections: 18,
  },
]

// Mock Extinguishers
export const mockExtinguishers: Extinguisher[] = [
  {
    id: 'e1',
    serialNumber: 'FE-2024-001',
    type: 'ABC',
    capacity: '10 lbs',
    location: 'Building A - Floor 1',
    customerId: 'cust1',
    customerName: 'Acme Corporation',
    companyId: 'c1',
    status: 'active',
    manufactureDate: '2023-01-15',
    expiryDate: '2029-01-15',
    lastInspectionDate: '2024-06-01',
    nextInspectionDate: '2024-12-01',
  },
  {
    id: 'e2',
    serialNumber: 'FE-2024-002',
    type: 'CO2',
    capacity: '15 lbs',
    location: 'Building A - Floor 2',
    customerId: 'cust1',
    customerName: 'Acme Corporation',
    companyId: 'c1',
    status: 'active',
    manufactureDate: '2023-03-20',
    expiryDate: '2029-03-20',
    lastInspectionDate: '2024-05-15',
    nextInspectionDate: '2024-11-15',
  },
  {
    id: 'e3',
    serialNumber: 'FE-2024-003',
    type: 'Water',
    capacity: '2.5 gal',
    location: 'Building B - Lobby',
    customerId: 'cust2',
    customerName: 'TechStart Inc.',
    companyId: 'c1',
    status: 'expired',
    manufactureDate: '2018-06-10',
    expiryDate: '2024-06-10',
    lastInspectionDate: '2024-01-10',
    nextInspectionDate: '2024-07-10',
  },
  {
    id: 'e4',
    serialNumber: 'FE-2024-004',
    type: 'Foam',
    capacity: '6 liter',
    location: 'Building C - Kitchen',
    customerId: 'cust2',
    customerName: 'TechStart Inc.',
    companyId: 'c1',
    status: 'maintenance',
    manufactureDate: '2022-09-05',
    expiryDate: '2028-09-05',
    lastInspectionDate: '2024-04-20',
    nextInspectionDate: '2024-10-20',
    notes: 'Pressure gauge needs replacement',
  },
  {
    id: 'e5',
    serialNumber: 'FE-2024-005',
    type: 'Dry Chemical',
    capacity: '20 lbs',
    location: 'Warehouse - Section A',
    customerId: 'cust3',
    customerName: 'Global Logistics',
    companyId: 'c1',
    status: 'active',
    manufactureDate: '2024-01-01',
    expiryDate: '2030-01-01',
    lastInspectionDate: '2024-07-01',
    nextInspectionDate: '2025-01-01',
  },
]

// Mock Inspections
export const mockInspections: Inspection[] = [
  {
    id: 'i1',
    extinguisherId: 'e1',
    extinguisherSerial: 'FE-2024-001',
    inspectorId: '4',
    inspectorName: 'Emily Inspector',
    customerId: 'cust1',
    customerName: 'Acme Corporation',
    companyId: 'c1',
    scheduledDate: '2024-12-01',
    status: 'scheduled',
  },
  {
    id: 'i2',
    extinguisherId: 'e2',
    extinguisherSerial: 'FE-2024-002',
    inspectorId: '4',
    inspectorName: 'Emily Inspector',
    customerId: 'cust1',
    customerName: 'Acme Corporation',
    companyId: 'c1',
    scheduledDate: '2024-11-15',
    status: 'scheduled',
  },
  {
    id: 'i3',
    extinguisherId: 'e3',
    extinguisherSerial: 'FE-2024-003',
    inspectorId: '4',
    inspectorName: 'Emily Inspector',
    customerId: 'cust2',
    customerName: 'TechStart Inc.',
    companyId: 'c1',
    scheduledDate: '2024-07-10',
    completedDate: '2024-07-10',
    status: 'completed',
    result: 'fail',
    notes: 'Extinguisher expired, recommended replacement',
  },
  {
    id: 'i4',
    extinguisherId: 'e4',
    extinguisherSerial: 'FE-2024-004',
    inspectorId: '4',
    inspectorName: 'Emily Inspector',
    customerId: 'cust2',
    customerName: 'TechStart Inc.',
    companyId: 'c1',
    scheduledDate: '2024-10-20',
    status: 'in_progress',
  },
]

// Mock Invoices
export const mockInvoices: Invoice[] = [
  {
    id: 'inv1',
    invoiceNumber: 'INV-2024-001',
    customerId: 'cust1',
    customerName: 'Acme Corporation',
    companyId: 'c1',
    amount: 450.00,
    tax: 36.00,
    total: 486.00,
    status: 'paid',
    dueDate: '2024-07-15',
    paidDate: '2024-07-10',
    items: [
      { description: 'Annual Inspection (10 units)', quantity: 10, unitPrice: 45, total: 450 },
    ],
    createdAt: '2024-06-15',
  },
  {
    id: 'inv2',
    invoiceNumber: 'INV-2024-002',
    customerId: 'cust2',
    customerName: 'TechStart Inc.',
    companyId: 'c1',
    amount: 225.00,
    tax: 18.00,
    total: 243.00,
    status: 'sent',
    dueDate: '2024-08-01',
    items: [
      { description: 'Annual Inspection (5 units)', quantity: 5, unitPrice: 45, total: 225 },
    ],
    createdAt: '2024-07-01',
  },
  {
    id: 'inv3',
    invoiceNumber: 'INV-2024-003',
    customerId: 'cust3',
    customerName: 'Global Logistics',
    companyId: 'c1',
    amount: 900.00,
    tax: 72.00,
    total: 972.00,
    status: 'overdue',
    dueDate: '2024-06-01',
    items: [
      { description: 'Annual Inspection (15 units)', quantity: 15, unitPrice: 45, total: 675 },
      { description: 'Maintenance Service', quantity: 3, unitPrice: 75, total: 225 },
    ],
    createdAt: '2024-05-01',
  },
]

// Mock Customers — id is number to match backend User type
export const mockCustomers: User[] = [
  {
    id: 101,
    email: 'contact@acme.com',
    firstName: 'Acme',
    lastName: 'Corporation',
    name: 'Acme Corporation',
    role: 'customer',
    companyId: 1,
    phone: '+1 (555) 111-2222',
    createdAt: '2024-01-20',
    isActive: true,
  },
  {
    id: 102,
    email: 'admin@techstart.com',
    firstName: 'TechStart',
    lastName: 'Inc.',
    name: 'TechStart Inc.',
    role: 'customer',
    companyId: 1,
    phone: '+1 (555) 333-4444',
    createdAt: '2024-02-15',
    isActive: true,
  },
  {
    id: 103,
    email: 'safety@globallogistics.com',
    firstName: 'Global',
    lastName: 'Logistics',
    name: 'Global Logistics',
    role: 'customer',
    companyId: 1,
    phone: '+1 (555) 555-6666',
    createdAt: '2024-03-10',
    isActive: true,
  },
]

// Mock Inspectors
export const mockInspectors: User[] = [
  {
    id: 4,
    email: 'emily@fms.com',
    firstName: 'Emily',
    lastName: 'Inspector',
    name: 'Emily Inspector',
    role: 'inspector',
    companyId: 1,
    phone: '+1 (555) 777-8888',
    createdAt: '2024-02-15',
    isActive: true,
  },
  {
    id: 5,
    email: 'david@fms.com',
    firstName: 'David',
    lastName: 'Chen',
    name: 'David Chen',
    role: 'inspector',
    companyId: 1,
    phone: '+1 (555) 888-9999',
    createdAt: '2024-03-01',
    isActive: true,
  },
  {
    id: 6,
    email: 'lisa@fms.com',
    firstName: 'Lisa',
    lastName: 'Martinez',
    name: 'Lisa Martinez',
    role: 'inspector',
    companyId: 2,
    phone: '+1 (555) 999-0000',
    createdAt: '2024-04-10',
    isActive: true,
  },
]
